### ISSUE TITLE
Inconsistent zone status

### ISSUE THREAD

**Issue by luixal** [rgc99/irrigation_unlimited#107]
**Describe the bug**
Hi,

I'm building a custom card for representing zones. Everything works well, but I find the `status` field quite inconsistent. I'll explain:

In this card I show the next irrigation date, using the `next_start` field. Thing is, when I disable a sequence, it updates this field, which is great but, when I disable the controller itself, it doesn't update this field. This may be due to the fact that disabling the controller doesn't disable sequences, which a right thing (I have many sequences, some disabled, if this disabled and reenables all of them it would be a nightmare!), but I think the `next_start` field should be updated as if the controller is disabled, there's no next start for any sequence and so, there's no next start for any zone.

Digging around, I noticed the `state` field taking a value of `blocked`, which is great, as it doesn't affect the `enabled` field. Would save me a lot of conditions/code, but it's also inconsistent: if I disable the controller, sequences get a `state` of `blocked`, same thing for the zones (great!) but, if I disable a sequence, zones keep state to `off` instead of `blocked`.

Wouldn't it make sense to update the `state` field from controller to sequences and to zones, the whole path?

**To Reproduce**
1. Disable the controller
2. Check sequence and zone `state` field. Both are set to `blocked`
3. Enable the controller
4. Disable the sequence
5. Check zone's `state` field, it's set to `off` while it should be set to `blocked`

**Expected behavior**
Use kind of a casade logic. Update the `state` field from controller to sequences and to zones.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Doesn't matter but tested in Arch Linux and Windows
 - Browser: Chrome and Firefox
 - Version: last

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20
 - OS: Android 13
 - Browser: Chrome and HA app
 - Version: latest

**Additional context**

**Comment by rgc99** [comment]
The `next_start` attributes along with `next_name` and `next_duration` are dynamically displayed. If there is no next schedule then they are not displayed. It may be best to use the `next_zone` attribute on the controller or the `next_schedule` on the zone which are always displayed but will contain a number or 'none'.

Item 5: This behaviour is correct. Disabling a sequence does not block the referenced zone(s). Consider a second sequence that referenced the same zones. Disabling the first sequence still leaves the second operable.

Zones are a representation of the physical valve. Sequences are a virtual 'playlist' of zones. Zones and sequences are both direct descendants of the controller, in other words they are siblings. Whilst they influence each other they do not control. Sequences recognise disabled zones and skip them. Zones recognise disabled sequences and ignore.

**Comment by luixal** [comment]
Maybe I've hit a weird scenario that makes this behaviour inconsistent from my point of view.

According to this part of your comment:

> The next_start attributes along with next_name and next_duration are dynamically displayed. If there is no next schedule then they are not displayed. It may be best to use the next_zone attribute on the controller or the next_schedule on the zone which are always displayed but will contain a number or 'none'.

and this one:

>Sequences recognise disabled zones and skip them. Zones recognise disabled sequences and ignore.

If no irrigation is really gonna happen, `next_start` on the zone should be `none`, an empty value or anything else, did i got it right?

Thing is, having the controller disabled, the sequence disabled or even the zone disabled, `next_start` keeps having a valid value. Even having the three of them disabled at the same time, `next_start` and `next_schedule` have a valid value.

Thinking about the value in `next_schedule` (2), make me think about something that can be affecting this. I have tow different sequences, one which has an schedule and a second one that hasn't. Differences are that the first one has different durations for some zones and the second one has the same duration for every zone. I use the second one (without a schedule) to make short manual irrigations (like 1min) after mowning.

I tried disabling everything (controller, both sequences and the zone) and it's `next_start` and `next_schedule` keep having a valid values:

```
enabled: false
friendly_name: "Zona 1"
next_duration: "0:07:30" <--- this duration comes from sequence 1, which is disabled
next_schedule: 2
next_start: "2023-05-24T21:00:00+02:00" <--- this comes from schedule 2 of sequence 1
```

In fact, I started working the zone cards based on the `next_start` field, but pivoted when saw this behaviour.

Can this be related to having a sequence without schedule?

This is my configuration.

```yaml
# Irrigation Unlimited
irrigation_unlimited:
  controllers:
    zones:
      - name: "Zona 1"
        entity_id: "switch.rain_bird_sprinkler_1"
      - name: "Zona 2"
        entity_id: "switch.rain_bird_sprinkler_2"
      - name: "Zona 3"
        entity_id: "switch.rain_bird_sprinkler_3"
      - name: "Zona 4"
        entity_id: "switch.rain_bird_sprinkler_4"
      - name: "Zona 5"
        entity_id: "switch.rain_bird_sprinkler_5"
      - name: "Zona 6"
        entity_id: "switch.rain_bird_sprinkler_6"
      - name: "Zona 7"
        entity_id: "switch.rain_bird_sprinkler_7"
    sequences:
      - name: "Diario"
        delay: "00:00:10"
        schedules:
          - name: "Mañana"
            time: "06:00"
          - name: "Tarde"
            time: "21:00"
        zones:
          - zone_id: 1
            duration: "00:10"
          - zone_id: 2
            duration: "00:10"
          - zone_id: 3
            duration: "00:6"
          - zone_id: 4
            duration: "00:8"
          - zone_id: 5
            duration: "00:8"
          - zone_id: 6
            duration: "00:8"
          - zone_id: 7
            duration: "00:6"
      - name: "Corto 5min"
        delay: "00:00:10"
        duration: "00:05"
        zones:
          - zone_id: 1
          - zone_id: 2
          - zone_id: 3
          - zone_id: 4
          - zone_id: 5
          - zone_id: 6
          - zone_id: 7
```

Thanks!

**Comment by rgc99** [comment]
Here I have used your config and disabled zone 1. Notice the `next_start`, `next_duration` and `next_name` fields are missing. Compare that to zone 2 which is enabled.
<img width="815" alt="Screen Shot 2023-05-26 at 1 39 27 pm" src="https://github.com/rgc99/irrigation_unlimited/assets/13636007/ae15ef77-b3dd-4d2c-8b5f-4366727575b5">

**Comment by luixal** [comment]
That's why I think there's some kind of weird behaviour when controller o sequence are previously disabled. Check this (controller previously disabled, then I disable zone):

![image](https://github.com/rgc99/irrigation_unlimited/assets/615268/02e367b3-1f82-4008-9a92-815d9f3830c0)

When controller is enabled and I disable the zone, it works well:

![image](https://github.com/rgc99/irrigation_unlimited/assets/615268/ed86522f-1ef9-4504-b6a3-b29c18702ace)


Same happens if I disable the controller and then the sequence, zone still has a `next_duration` _"valid"_ date.

I guess that, if controller is already disabled, changes in sequences and zones states are not applied/reflected/propagated.

One quick solution is to set to null this fields when controller is disabled, but maybe is some much simpler as some function not being executed when controller is disabled.

**Comment by rgc99** [comment]
Struggling to reproduce this. I need the log entries in particular the service calls i.e.
```
2023-05-26 22:55:21.212 INFO (MainThread) [custom_components.irrigation_unlimited] CALL [2023-05-27 08:55:21] service: disable, controller: 1, zone: 1, data: {}
```

Perhaps even turn on debug level by adding this to the configuration.yaml
```
logger:
  default: info
  logs:
    custom_components.irrigation_unlimited: debug
```

**Comment by luixal** [comment]
Ok, let's see if I can give you the info you need clearly.

All my test start with Irrigation controller, sequence and zones are all enabled.

### Calling toggle service on controller

I call `toggle `service like this:

```yaml
service: irrigation_unlimited.toggle
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_m
  zones: 1
```

I get this log entry:

```
2023-05-29 09:37:54.480 INFO (MainThread) [custom_components.irrigation_unlimited] CALL [2023-05-29 09:37:54] service: toggle, controller: 1, zone: 0, data: {"entity_id": ["binary_sensor.irrigation_unlimited_c1_m"], "zones": [1]}
```

One thing here, I already saw that, zone if not disabled, main controller is (so sequence has no `start` datetime, but zone has). If I want to disable zone I have to call the same service using the zone as entity_id, like this:

```yaml
service: irrigation_unlimited.toggle
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_z1
```

I get this log entry:

```
2023-05-29 09:49:36.901 INFO (MainThread) [custom_components.irrigation_unlimited] CALL [2023-05-29 09:49:36] service: toggle, controller: 1, zone: 1, data: {"entity_id": ["binary_sensor.irrigation_unlimited_c1_z1"]}
```

Zone is now disabled, but it still has fields populated, `next_start` included.

### Calling toggle service on sequence

I call the service like this:

```yaml
service: irrigation_unlimited.toggle
data:
  entity_id: binary_sensor.irrigation_unlimited_c1_m
  sequence_id: 1
```

I get this log entry:

```
2023-05-29 09:46:56.953 INFO (MainThread) [custom_components.irrigation_unlimited] CALL [2023-05-29 09:46:56] service: toggle, controller: 1, zone: 0, data: {"entity_id": ["binary_sensor.irrigation_unlimited_c1_m"], "sequence_id": 1}
```

Sequence is disabled and zone has no `next_start` field.

### Conclusions
Without having dig into the code, it seems like disabling a sequence correctly update zones, but disabling the main controller doesn't.

**Comment by rgc99** [comment]
Unable to reproduce this on my development machine. It may have been fixed as part of some other work in this area. A lot of the parameters to the service calls now support templates. This gives a great deal of flexibility when calling from custom cards that don't offer this ability.

If you are ok to do a manual instal then replace all the files in config/custom_components/irrigation_unlimited with the ones from the [repository](https://github.com/rgc99/irrigation_unlimited/tree/master/custom_components/irrigation_unlimited) (note: there is one new module `schema.py`). If anything goes wrong then simply reinstall from hacs. This would be the most helpful way.

**Comment by luixal** [comment]
Hi @rgc99 , not sure If I understand.

Do you mean doing kind of a manual reinstall or are those files different to the ones installed by HACS? I already have the `schema.py` file

Just updated this to the latest version, but still happening (if controller is disabled, zone status is set to blocked, next_start stays set and zone is never updated until I enable the controller).

**Comment by luixal** [comment]
Didn't see this coming. Just clone the repo and compare both directories, `schema.py` files were slitghtly different.

Sadly, replacing the local install with the file from the repo, didn't do the trick. I'm still having the bug.

Differences were at lines 211 and 227 (can contains typos, HA console didn't want me to copy and paste...):

```py
# line 211 on local install
vol.Optional(CONF_DELAY): cv.positive_time_period,
# line 211 on repo
vol.Optional(CONF_DELAY): cv.time_period,

# line 227 on local install
vol.Optional(CONF_DELAY): cv.positive_time_period,
# line 227 on repo
vol.Optional(CONF_DELAY): cv.time_period,
```

They seem to me just like default values to apply when loading config.

Tried making a new install con HACS and restarting HA, but nothings seems to work. This is still happening :(

By the way, I've also noticed that disabling the controller using the card, does nothing, only calling the service disables it.
